// <auto-generated />
using System;
using AgdtTestTask.Medical.DataAccess.EF.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgdtTestTask.Medical.DataAccess.Migrations.Migrations
{
    [DbContext(typeof(AgdtMedicalDbContext))]
    partial class AgdtMedicalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgdtTestTask.Medical.Entities.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Birthdate");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("AgdtTestTask.Medical.Entities.Patient", b =>
                {
                    b.OwnsOne("AgdtTestTask.Medical.Entities.Name", "Name", b1 =>
                        {
                            b1.Property<long>("PatientId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Family")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Use")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PatientId");

                            b1.HasIndex("Id")
                                .IsUnique()
                                .HasFilter("[Id] IS NOT NULL");

                            b1.ToTable("PatientName", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PatientId");

                            b1.OwnsMany("AgdtTestTask.Medical.Entities.GivenName", "Given", b2 =>
                                {
                                    b2.Property<long>("PatientId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Value")
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.HasKey("PatientId", "Value");

                                    b2.ToTable("PatientGivenName", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PatientId");
                                });

                            b1.Navigation("Given");
                        });

                    b.Navigation("Name");
                });
#pragma warning restore 612, 618
        }
    }
}
