services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: agdt-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_USER: ${DB_USER}
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql   
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U \"$$SA_USER\" -P \"$$SA_PASSWORD\" -C -Q \"SELECT 1\" || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10


  migrations:
    build:
      context: .
      dockerfile: AgdtTestTask.Medical.DataAccess.Migrations/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}
    restart: "no"

  webapi:
    build:
      context: .
      dockerfile: AgdtTestTask.Medical.WebApi/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}

volumes:
  sql_data:
